# Generated by Django 6.0.4 on 2026-04-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trailer_url", models.CharField(max_length=200)),
                ("img_src", models.CharField(max_length=200)),
                ("img_alt", models.CharField(max_length=100)),
                ("img_width", models.IntegerField()),
                ("img_height", models.IntegerField()),
                ("description", models.CharField()),
                ("duration", models.DurationField()),
            ],
        ),
    ]
