# Generated by Django 6.0.4 on 2026-04-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmReviewApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trailer",
            name="duration",
            field=models.CharField(verbose_name=10),
        ),
    ]
