# Generated by Django 6.0.4 on 2026-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmReviewApp", "0003_slider"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("anchor_class", models.CharField(max_length=2)),
                ("icon_class", models.CharField(max_length=30)),
                ("url", models.CharField(max_length=200)),
            ],
        ),
    ]
