# Generated by Django 6.0.4 on 2026-04-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmReviewApp", "0004_sociallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=7)),
            ],
        ),
    ]
