# Generated by Django 6.0.4 on 2026-04-20 22:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmReviewApp", "0005_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="movie_genre",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10), blank=True, default=list
            ),
        ),
    ]
