# Generated by Django 6.0.4 on 2026-04-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmReviewApp", "0007_alter_genre_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slider",
            name="movie_genre",
        ),
        migrations.AddField(
            model_name="slider",
            name="movie_genre",
            field=models.ManyToManyField(
                blank=True, related_name="sliders", to="filmReviewApp.genre"
            ),
        ),
    ]
