# Generated by Django 6.0.4 on 2026-04-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filmReviewApp", "0008_remove_slider_movie_genre_slider_movie_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="slider",
            old_name="movie_genre",
            new_name="movie_genres",
        ),
    ]
