# Generated by Django 6.0.4 on 2026-04-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmReviewApp', '0010_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('featured', 'Featured'), ('extra', 'Extra')], max_length=20)),
                ('img_src', models.CharField(max_length=200)),
                ('img_alt', models.CharField(max_length=100)),
                ('img_width', models.IntegerField()),
                ('img_height', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
