# Generated by Django 6.0.4 on 2026-04-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmReviewApp', '0011_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_alt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
