# Generated by Django 6.0.4 on 2026-04-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmReviewApp', '0012_alter_news_img_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_src',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
