# Generated by Django 6.0.4 on 2026-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filmReviewApp", "0014_tweet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Celebrity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_width", models.IntegerField()),
                ("img_height", models.IntegerField()),
                ("anchor_url", models.CharField(max_length=200)),
                ("celebrity_name", models.CharField(max_length=50)),
                ("celebrity_url", models.CharField(max_length=200)),
                ("celebrity_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="MovieTheater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("img_width", models.IntegerField()),
                ("img_height", models.IntegerField()),
                ("img_src", models.CharField(max_length=200)),
                ("anchor_url", models.CharField(max_length=200)),
                ("lower_rating", models.CharField(max_length=5)),
                ("upper_rating", models.CharField(max_length=5)),
                ("movie_genre", models.CharField(max_length=10)),
                ("movie_title", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="MovieTv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("img_width", models.IntegerField()),
                ("img_height", models.IntegerField()),
                ("img_src", models.CharField(max_length=200)),
                ("anchor_url", models.CharField(max_length=200)),
                ("lower_rating", models.CharField(max_length=5)),
                ("upper_rating", models.CharField(max_length=5)),
                ("movie_genre", models.CharField(max_length=10)),
                ("movie_title", models.CharField(max_length=20)),
            ],
        ),
    ]
