# Generated by Django 6.0.4 on 2026-04-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmReviewApp', '0015_celebrity_movietheater_movietv'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='img_src',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
